pool:
  vmImage: 'macos-latest'

pr:
  branches:
    include:
    - master

trigger:
- master

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetVersion: '1.1.$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  inputs:
    solution: '**/CalendarPlugin.csproj'
    msbuildArchitecture: 'x64'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/p:Version=$(nugetVersion) /p:AppendTargetFrameworkToOutputPath=true /p:BaseOutputPath=$(Build.ArtifactStagingDirectory)\'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: nupkg'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(BuildPlatform)/$(BuildConfiguration)/'
    ArtifactName: nupkg

- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android project SampleApp.Android.csproj'
  inputs:
    projectFile: '**/SampleApp.Android.csproj'
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: '$(BuildConfiguration)'
    msbuildVersionOption: latest


